/**
 * Daily HTML Template Generator Script
 * 
 * This script is intended to be run by GitHub Actions daily.
 * It calls the Ollama Cloud API (or any LLM API you prefer) to generate
 * a raw HTML/CSS template, saves it to `public/templates/`, and updates
 * the `src/data/templates.js` registry so it appears on the dashboard.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Replace these with your actual Ollama endpoints and models
const OLLAMA_URL = process.env.OLLAMA_API_URL || 'http://localhost:11434/api/generate';
const OLLAMA_KEY = process.env.OLLAMA_API_KEY || ''; // If required by your cloud setup

async function generateTemplate() {
  console.log('Starting daily template generation...');
  
  // 1. Define the prompt for Ollama
  const prompt = `
    You are an expert web designer. Create a stunning, single-file HTML/CSS template.
    Use modern design principles, clean code, and responsive design.
    The CSS should use CSS variables for colors so it can be themed.
    
    Variables to support:
    --primary
    --bg-main
    --bg-surface
    --text-primary
    --text-secondary
    --border
    
    Output ONLY raw valid HTML code. Do not include markdown blocks like \`\`\`html.
  `;

  try {
    // 2. Call the Ollama API
    // NOTE: This is a stub! Replace the fetch call with your actual Ollama API configuration.
    /*
    const response = await fetch(OLLAMA_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${OLLAMA_KEY}`
      },
      body: JSON.stringify({
        model: 'llama3', // or your preferred model
        prompt: prompt,
        stream: false
      })
    });
    
    if (!response.ok) throw new Error(`Ollama API Error: ${response.status}`);
    const data = await response.json();
    const htmlContent = data.response;
    */

    // ----- STUB FOR DEMONSTRATION -----
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AI Generated Template</title>
    <style>
        body { font-family: sans-serif; background: var(--bg-main, #f8fafc); color: var(--text-primary, #0f172a); padding: 2rem; }
        .box { background: var(--bg-surface, #fff); border: 1px solid var(--border, #e2e8f0); padding: 2rem; border-radius: 0.5rem; text-align: center; }
        h1 { color: var(--primary, #8b5cf6); }
    </style>
</head>
<body>
    <div class="box">
        <h1>Generated by Ollama</h1>
        <p>This is a placeholder generated template. Connect your API to see real generated templates here!</p>
    </div>
</body>
</html>`;
    // ----------------------------------

    // 3. Save to public/templates/
    const dateStr = new Date().toISOString().split('T')[0];
    const templateId = `ai-template-${Date.now()}`;
    const filename = `${templateId}.html`;
    const filepath = path.join(__dirname, '..', 'public', 'templates', filename);
    
    fs.writeFileSync(filepath, htmlContent, 'utf-8');
    console.log(`✅ Saved new template to ${filepath}`);

    // 4. Update the src/data/templates.js file to include the new template
    const metadataPath = path.join(__dirname, '..', 'src', 'data', 'templates.js');
    let metadataContent = fs.readFileSync(metadataPath, 'utf-8');
    
    const newEntry = `  {
    id: '${templateId}',
    title: 'AI Generated Template (${dateStr})',
    description: 'A brand new layout generated automatically by Ollama AI.',
    dateAdded: '${dateStr}',
    fileUrl: '/templates/${filename}',
    category: 'Generated',
    thumbnail: 'https://images.unsplash.com/photo-1620121692029-d088224ddc74?auto=format&fit=crop&q=80&w=800'
  }`;

    // Insert the new entry into the array (find the opening bracket and insert after)
    metadataContent = metadataContent.replace(
      'export const templates = [',
      `export const templates = [\n${newEntry},`
    );

    fs.writeFileSync(metadataPath, metadataContent, 'utf-8');
    console.log('✅ Updated templates.js with new entry');
    console.log('Generation complete!');

  } catch (error) {
    console.error('Failed to generate template:', error);
    process.exit(1);
  }
}

generateTemplate();
